[package]
name = "evaera/promise"
description = "Promise implementation for Roblox"
version = "4.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
